version: '3.8'
services:
  # Grafana LGTM Stack
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"  # Grafana UI
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP

  # C# WebAPI application
  webapi:
    build: 
      context: ./OtelLgtmDemo  # Change the context to the project directory
      dockerfile: ../Dockerfile     # Adjust dockerfile path
    ports:
      - "5000:80"                   # Map to port 80 inside the container
    depends_on:
      - otel-lgtm
    environment:
      - ASPNETCORE_URLS=http://+:80  # Change to port 80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317